# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X9YXo_sz36XwmV0QP2v9-ZhvznyP9bbr
"""

import random
tries = 0
print('Угадай число от 1 до 100')
a = random.randint(1, 100)
while True:
  b = int(input('Введите число:'))
  if a > b:
    tries += 1
    print('Число больше')
  elif a < b:
    tries += 1
    print('Число меньше')
  elif a == b:
    tries +=1
    print('Вы угадали', a)
    print('Ваше количество попыток:', tries)
    c = input('Продолжаешь?(yes/no)')
    if c == 'yes':
      print('Угадай число от 1 до 100')
      a = random.randint(1, 100)
      tries = 0
    else:
      print('Пока')
      break