# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r9LzpwyGV8YqCwsQMUhT8r-Ne57Ym6Mr
"""

import random
player_score = 0
pc_score = 0
while True:
  computer = (random.randint(1, 3)) # 1 - stone 2 - noz 3 - paper
  player = int(input('Введите свой вариант(1 - stone 2 - noz 3 - paper):'))
  if computer == player:
    print('Ничья')
  elif(player == 1 and computer == 2) or (player == 2 and computer == 3) or (player == 3 and computer == 1):
    player_score += 1
    print('Победа')
  else:
    pc_score += 1
    print('Поражение')
  if player_score == 3 or pc_score == 3:
    print('Ты победил') if player_score == 3 else print('Ты проиграл')
    break